apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx-hello
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/zatkowich/photoneo-test.git
