apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-hello
  namespace: flux-system
spec:
  dependsOn:
    - name: ngrok-ingress-controller
  path: ./k8s/deployments/apps/nginx-hello
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m
  wait: true
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: deployments
