apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ngrok-ingress-controller
  namespace: flux-system
spec:
  path: ./k8s/deployments/system/ngrok-ingress-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m
  wait: true
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: deployments
